name: CD Pipeline

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        variant: ["cpu", "gpu"]
    steps:
      - uses: actions/checkout@v4
      
      - name: Debug directory structure
        run: |
          echo "Current working directory: $(pwd)"
          echo "Contents of docker directory:"
          ls -la docker/
          echo "Checking for Dockerfile.${{ matrix.variant }}"
      
      - name: Verify Dockerfiles exist
        run: |
          if [ ! -f "docker/Dockerfile.${{ matrix.variant }}" ]; then
            echo "::error::docker/Dockerfile.${{ matrix.variant }} not found!"
            exit 1
          fi
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          install: true
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      
      - name: Build and Push Docker Images
        uses: docker/build-push-action@v4
        with:
          context: .
          file: docker/Dockerfile.${{ matrix.variant }}
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/your-repo:latest-${{ matrix.variant }}
            ${{ secrets.DOCKER_HUB_USERNAME }}/your-repo:${{ github.sha }}-${{ matrix.variant }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            BUILDKIT_INLINE_CACHE=1