name: CI Pipeline

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  lint_and_format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
          
      - name: Install Ruff
        run: pip install ruff==0.3.7
          
      - name: Lint with Ruff
        run: ruff check .
        
      - name: Check Formatting
        run: ruff format --check .

  build_docker:
    needs: lint_and_format
    runs-on: ubuntu-latest
    strategy:
      matrix:
        variant: ["cpu", "gpu"]
    steps:
      - uses: actions/checkout@v4
      
      - name: Verify Dockerfiles exist
        run: |
          echo "Current directory: $(pwd)"
          echo "Dockerfiles found:"
          ls -la docker/Dockerfile.* || true
          if [ ! -f "docker/Dockerfile.${{ matrix.variant }}" ]; then
            echo "::error::docker/Dockerfile.${{ matrix.variant }} not found!"
            exit 1
          fi
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Build Docker Images
        uses: docker/build-push-action@v4
        with:
          context: .
          file: docker/Dockerfile.${{ matrix.variant }}
          tags: |
            your-repo-ci:${{ github.sha }}-${{ matrix.variant }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          outputs: type=docker